### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by architkshk** [hereisnaman/gitfame-backend#32]
I am getting this error during the project setup.

`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn redis-server ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:686:11)
    at Object.<anonymous> (/home/archit/Documents/wor/api.gitfa.me/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

**Comment by 0xnmn** [comment]
@architkshk did you create the env file ?

**Comment by architkshk** [comment]
@hereisnaman Yes.

**Comment by 0xnmn** [comment]
@architkshk have you installed redis ?

**Comment by architkshk** [comment]
Yes. The problem Is solved now. I just removed the node_modules folder, cleaned yarn cache and reinstalled. 
Sorry to bother you.
Thank You.
